run:
  skip-dirs:
    - src/external_libs
  skip-files:
    - ".*\\.my\\.go$"
    - lib/bad.go

linters:
  enable-all: true
  disable:
    - maligned
    - prealloc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gosec
        - staticcheck
        - unparam
