version: "3.8"
services:

  test:
    build:
      context: docker/test-runner
      dockerfile: Dockerfile
      args:
        GO_VERSION: ${GO_VERSION:-1.18.1}
    depends_on:
      - rdb
      - migration
    volumes:
      - $PWD:/go/src/github.com/rymiyamoto/memer
    environment:
      GO_ENV: ${GO_ENV:-test}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-test}
      DB_ADDRESS: ${DB_ADDRESS:-rdb}
      DB_SCHEMA: ${DB_DATABASE:-memer}
      DB_PORT: ${DB_PORT:-3306}
    working_dir: /go/src/github.com/rymiyamoto/memer

  migration:
    build:
      context: .
      dockerfile: docker/migration/Dockerfile
      args:
        GO_VERSION: ${GO_VERSION:-1.18.1}
    depends_on:
      - rdb
    volumes:
      - $PWD:/go/src/github.com/rymiyamoto/memer
    environment:
      GO_ENV: ${GO_ENV:-test}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-test}
      DB_ADDRESS: ${DB_ADDRESS:-rdb}
      DB_SCHEMA: ${DB_SCHEMA:-memer}
      DB_PORT: ${DB_PORT:-3306}
    working_dir: /go/src/github.com/rymiyamoto/memer
    command:
      - "sql-migrate"
      - "up"
      - "-config=asset/db/dbconf.yml"
      - "-env=${GO_ENV:-test}"

  rdb:
    image: arm64v8/mysql:8.0-oracle
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: ${DB_USER:-root}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-test}
      MYSQL_DATABASE: ${DB_SCHEMA:-memer}
    command:
      - --collation-server=utf8mb4_general_ci
      - --default-storage-engine=innodb
      - --default_authentication_plugin=caching_sha2_password
